### ISSUE TITLE
Nano Swarm

### ISSUE THREAD

**Issue by Nohicom** [austinv11/PeripheralsPlusPlus#101]
How do I call a Nano Swarm? I've thrown one into myself to try to read information about my player, but I won't work. The current code is just a test that reads what entites are connected, whether one is a player, and what the player name is.

The Code:
![nano1](https://cloud.githubusercontent.com/assets/7751431/9023712/f850f6d4-386c-11e5-95c4-db007e6cc101.png)

What Happens:
![nano2](https://cloud.githubusercontent.com/assets/7751431/9023713/003814c2-386d-11e5-9564-7eb92be033fd.png)

Am I calling it wrong? How do the Nano Swarms work?

**Comment by grandmind** [comment]
isPlayer() is not a function of the antenna. It is a function of the player object which can be accessed with getInfectedEntities().

**Comment by Nohicom** [comment]
So how would I use that in code? Which player object do I call/how do I
find it?

**Comment by Pyeroh** [comment]
In your example, "bots" is an array with all entities connected to the antenna through nano swarms. For each entity in this array, you can use .isPlayer() to know if it's a player or not, and then get specifically your player entity. After that, you can use player methods on this entity.
More generally, when you get stuck with a method, read the docs, and try using methods through the lua interpreter in a computer ;)

**Comment by grandmind** [comment]
I might be misunderstanding you, but I'm pretty sure that in his example, "bots" in the antenna peripheral. He can get the entities array with the getInfectedEntities() function.

**Comment by Nohicom** [comment]
I understand that I would use the getInfectedEntities() somehow, but how I
go about doing that specifically?

For instance, if I wanted to test for ".isPlayer()", would I do
"bots.getInfectedEntities().isPlayer()"? how would I get the individual
entities to test/interact with?

**Comment by grandmind** [comment]
The method returns an array of all the infected entities on which you can perform those functions.

**Comment by Nohicom** [comment]
Yes, how? I understand that I use that method to do so, but give me a
specific example of the code I would use, within the screenshot examples,
to specifically test whether entity 77 (me) is a player?

**Comment by grandmind** [comment]
Um... how to access an array? 
antenna.getInfectedEntities()[1].isPlayer()

**Comment by Nohicom** [comment]
Alright, thank you. I was probably being exceptionally dumb today, most
likely out of lack of sleep, so thank you for all of your help and
patience. :)

**Comment by gravestristen** [comment]
Do you mind showing the finalized code?
