### ISSUE TITLE
Ridable turtle and turtle.up()

### ISSUE THREAD

**Issue by Matt-MTI** [austinv11/PeripheralsPlusPlus#103]
When riding a turtle and you use the command turtle.up() it says an object is in the way. Can it be changed that it checks for blocks above the player instead of above the turtle and then when you dismount it checks above the turtle. If that makes sense. Basically turtle.up() doesn't work when riding a turtle.

**Comment by austinv11** [comment]
It seems that ComputerCraft doesn't want to cooperate with the ridable turtle. I'll see what I can do, but unfortunately I doubt I can do much. Although manually going up or down does work properly.

**Comment by thejonathanr** [comment]
What is happening is turtles will stop if a player is in their way, so going up riding a turtle will not work unless someone changes something in the way ridable turtles detect players.

**Comment by austinv11** [comment]
Yes, I understand that. ComputerCraft handles turtle movement with the turtle.up() function, I handle it when done manually. So moving it manually will override the ComputerCraft turtle handling.

**Comment by Matt-MTI** [comment]
What do you mean by manually?

**Comment by austinv11** [comment]
By pressing the x button
