### ISSUE TITLE
[Bug] ME Bridge listAll() doesn't return GregTech item names correctly 

### ISSUE THREAD

**Issue by Muramasa-** [austinv11/PeripheralsPlusPlus#104]
Hi,

When I access the items in an AE system with the ME Bridge and print the display name of a GregTech item from the table it doesn't seem to output the correct display name.

Peripherals++ Version: 1.3.0-161

Code used
me = peripheral.wrap("back")
list = me.listAll()
print(list[45][4]) -- 45 being the index of a GT item, 4 being the display name of the item.

Output: gt.metaitem.01.2505.name

The rawid for the GT item is: gregtech:gt.metaitem.01 and the damage is 2505.

I really hope this can be fixed. Thanks.

**Comment by austinv11** [comment]
Sorry, there's nothing *I* can personally do about it, however you can try to bug greg as it seems to be his fault that display names aren't properly done

**Comment by grandmind** [comment]
Out of curiosity, what gregtech version are you using? And what item are you trying to get the name of? I tested a couple of items in the latest GT version and couln't replicate this.

**Comment by Muramasa-** [comment]
I am using GregTech 5.08.26 (BloodAsp's Build) and the item was olivine dust.

What environment can you read the correct display names?

**Comment by grandmind** [comment]
Ah, I was testing with GT6. Sadly, there's not much austin can do about this, as it's most likely a problem with the way the author is doing localization.

**Comment by Muramasa-** [comment]
Sorry to keep posting on this closed issue, but can you confirm that you can read the display names of GT items on GT6? and the version of GT6 you are using so I can pass the info to the GT5 Unofficial github.

Thanks.

**Comment by grandmind** [comment]
Gregtech 6 and 5 are so drastiacally, it hardly matters if it works on 6 and not 5. I took a quick look at that repo and the names of items aren't even being localized properly. I think that getting it working on 5 would require a complete reworking of how greg did item in terms of metadata and whatnot.
