### ISSUE TITLE
ME Bridges retrieve doesn't work

### ISSUE THREAD

**Issue by Nathan1852** [austinv11/PeripheralsPlusPlus#108]
The moethods doesn't actually retrieve the Imte, it only returns 0 and does nothing else.
I've tried it with the directions name and number, both don't work

**Comment by grandmind** [comment]
I was unable to reproduce this bug. Can I please get the version of Peirpherals++ and AE2 you are using as well as the command you are trying to execute.

**Comment by Nathan1852** [comment]
Strange, I tested it again and it worked this time. I probably did something wrong
