### ISSUE TITLE
Crash on "recipe usage"

### ISSUE THREAD

**Issue by Pyeroh** [austinv11/PeripheralsPlusPlus#113]
The game loads, but when I load a map, and try to see usage of an item (with NEI), it crashes : 
http://pastebin.com/W82501dR
The modlist is in the crashlog, but just to let you know, I use CC1.74, if there's anything related to this version...

PS : I tried removing NEIAddons and NEIIntegration, it crashed anyway

**Comment by grandmind** [comment]
This happens when you try to get the usage of <b>any</b> item?

**Comment by Pyeroh** [comment]
Yep. I tried with a few blocks :
- Wood log or computer (modded on non-modded item) : crashlog in the first post
- Turtle without upgrades or with PPP upgrade (upgradable turtle) : http://pastebin.com/WSdxWD2p

In case you would ask it, there's no problem when I try to get the recipe (R key with NEI) of any block.

**Comment by Pyeroh** [comment]
I tested your correction, and it works, but only if you search usage for a non-turtle item (all that's not a turtle, or an upgraded version).

**Comment by austinv11** [comment]
Can you give me the latest crash log?

**Comment by Pyeroh** [comment]
Sure : http://pastebin.com/VrBxUZhe

**Comment by Pyeroh** [comment]
"It's over, it's done"
It doesn't crash anymore !
Thank you for your mod, and your reactivity
