### ISSUE TITLE
Pocket peripherals are not cleared between sessions

### ISSUE THREAD

**Issue by SquidDev** [austinv11/PeripheralsPlusPlus#114]
The [cache of pocket peripherals](https://github.com/austinv11/PeripheralsPlusPlus/blob/master/src/main/java/com/austinv11/peripheralsplusplus/hooks/ComputerCraftHooks.java#L26-L27) does not appear to be cleared between world reloads.

Exiting a world and then loading it again without restarting Minecraft will preserve all existing peripherals. Clearing the cache with `onServerStart`/`onServerStopped` event handlers should prevent this.

**Comment by austinv11** [comment]
Sorry, I've been really busy preparing for school. I hope to get more time to mod soon.
