### ISSUE TITLE
Chatbox Coordinate Logging

### ISSUE THREAD

**Issue by FHRNet** [austinv11/PeripheralsPlusPlus#117]
Hi guys,
thanks for this great mod!  
  
Unfortunately it seems there is a problem with the ChatBox block, more specifically with the "B:logCoords" config option.  
I set this to "B:logCoords=false" so I could "label" the chatbox messages. Unfortunately, I still get the error message when using the command:

    lua> cb.say("message", 64, false, "Label")
    lua:1: Coordinate logging is enabled, disable this to enable naming

This happens on server, as well as on single player worlds. Doesn't matter if you use Computer or Advanced computer.

**Comment by austinv11** [comment]
What version of Peripherals++ are you using?

**Comment by austinv11** [comment]
Can you try deleting the config and trying again?

**Comment by FHRNet** [comment]
Hi,

I deleted the configuration file and now it works flawlessly. I noticed we used configuration file which had absolutely different syntax - probably from some very old version.

Thank you for your support

**Comment by austinv11** [comment]
Yeah sorry, that is due to the 1.3 update. I migrated to my own system of configurations

**Comment by FHRNet** [comment]
The problem with this appeared again after some config file adjustments.
I think you have a bug in the configuration system.

File that works: http://ovh.to/T8ND7Pg
File that does not work: http://ovh.to/XAych1G

They are almost same, except for one major thing: There are spaces on empty lines.
That causes the mod to ignore the config file completely.

**Comment by rolandoislas** [comment]
The working one appears to be using tab characters while the other one is using (8) spaces.

**Comment by austinv11** [comment]
Hm, should be a quick fix
