### ISSUE TITLE
ME Bridge server crash

### ISSUE THREAD

**Issue by cfarence** [austinv11/PeripheralsPlusPlus#120]
Server crashes when placing the ME bridge. I get the following error in the log "java.lang.NoClassDefFoundError". I'm using Applied Energistics 2 rv3.alpha build 6 and Computer Craft 1.74

Full Crash Report:
[Pastebin](http://pastebin.com/VVTA9HB5)

**Comment by grandmind** [comment]
Applied Energistics states that rv3 builds are to be used for testing only. They are considered unstable and incompatible with addons.
