### ISSUE TITLE
Causes ThermalExpansion crash when Installed

### ISSUE THREAD

**Issue by WiduX** [austinv11/PeripheralsPlusPlus#122]
When Peripherals++ v1.3.3 is installed with CollectiveFramework 1.0.0-132, alongside CoFHCore 3.0.3-303, ThermalFoundation 1.2.0-102, ThermalExpansion 4.0.3B1-218, and ThermalDynamics 1.1.0-161, the game will crash when attempting to remove a TE machine. After posting a report on CoFH's GitHub here: https://github.com/CoFH/Feedback/issues/860
I determined that the crash was only reproducible when Peripherals++ was installed. If Peripherals++ is removed, but CollectiveFramework remains installed, the crash no longer occurs.
The crash report can be found here: http://pastebin.com/1AKkZ2nH

**Comment by skyboy** [comment]
As a core mod you cannot include APIs from any other mod. FML is incapable of sorting coremods, or anything they include that is not theirs, in a meaningful manner.

**Comment by WiduX** [comment]
Yup, that would be the problem. After deleting the "cofh" folder from Peripherals++, I can no longer reproduce the crash.

**Comment by grandmind** [comment]
Hi, I wasn't able to reproduce this with the mods you listed. From your crash report, it appears you're running a pack with over 60 other mods. Would you mind getting a crash report with the mods you listed so I can try to reproduce it again?

**Comment by WiduX** [comment]
Huh. That's interesting. I can't reproduce it anymore, regardless of what mods I add or remove. Seems like it may simply be a problem with mod loading order, so it actually may not be Peripherals++.

**Comment by grandmind** [comment]
I assume it's a problem caused by Peripherals++ but not because of a conflict with a mod you listed. If you can figure out what mod is causing the issue out of the pack, I'll see if I can figure out the problem.

**Comment by WiduX** [comment]
Even more puzzling, I put all of the mods back, exactly how I had it when it was crashing, and I can't reproduce the crash. Odd...
