### ISSUE TITLE
Player Interface Crash on permission card GUI

### ISSUE THREAD

**Issue by alandoyle95** [austinv11/PeripheralsPlusPlus#123]
Custom modded server, go to add permissions to the card

Crash log from the server is here: http://pastebin.com/8anq305z

repeatable. 3 times. in a row.

if i forgot any info please let me know :)

Works on single player on the same pack. testing more on the server..

**Comment by alandoyle95** [comment]
Works on single player on the same pack. testing more on the server..

**Comment by grandmind** [comment]
This looks like an NEI crash. You can report it here: https://github.com/Chicken-Bones/NotEnoughItems

**Comment by alandoyle95** [comment]
and then i pull a stupid and post the wrong crash report..

http://pastebin.com/8anq305z

Here is the correct one

**Comment by alandoyle95** [comment]
I can confirm this is now fixed :) thanks!
