### ISSUE TITLE
Chunk loading Turtles not chunk loading

### ISSUE THREAD

**Issue by alandoyle95** [austinv11/PeripheralsPlusPlus#127]
Chunk loading turtles do no chunk load on servers, or single player.

turtles just reboot when you reload the chunks your self.

**Comment by grandmind** [comment]
Hi, I was able to use the chunk loading turtle perfectly. Could you give a little more information on what the turtle is doing (is it moving around, staying in the same spot, moving between chunks, etc.) so I can try to reproduce your bug?

**Comment by alandoyle95** [comment]
its running a quarry program in one chunk in a different DIM let me go triple check. that its not working..

**Comment by grandmind** [comment]
You might also check your config to make sure that nothing is out of place. 
This is what the default looks like and what I am using to test currently:
http://i.imgur.com/QLONB4o.png

**Comment by alandoyle95** [comment]
ahh, so it works 100% in the overworld. but when its in the Aroma1997's Dim it does not work

i made a video of this testing if you need to see it lol..

**Comment by grandmind** [comment]
Ah, ok, let me mess around with that for a bit and I'll see if I can fix it.

**Comment by alandoyle95** [comment]
spoke too soon, it was working in the overworld, but then after a while (while going back and forth between dim's the turtle turned off)

**Comment by grandmind** [comment]
Confirmed, chunk loading doesn't work at all in other dimensions. Travelling between dimensions is unrelated.

**Comment by alandoyle95** [comment]
awesome haha. glad this mod gets active work on it, love this mod XD

**Comment by TechOFreak** [comment]
Any progress on this bug? I have the same issue when in a rftools dimension. The moment I leave the turtle and chunks stop loading the turtle exits its program. When I return to the turtle starts back up.

**Comment by grandmind** [comment]
Forgot to reference this in 5b89e7dfc2ece7d66d3015ed3a9a4ae09a4c2bdd.
