### ISSUE TITLE
Player Interface suggestion

### ISSUE THREAD

**Issue by alandoyle95** [austinv11/PeripheralsPlusPlus#128]
it would be helpfull/nice if the player interface had a getAllStacks or getInventorySize method to go along with the getStackInSlot seeing there is no way for the computer to know the range of slot #'s the player has without counting or hard programming it into the turtle.

**Comment by grandmind** [comment]
I added getSize. With that information, it's pretty easy to get all of the stacks just with a loop.

**Comment by alandoyle95** [comment]
seems to be thoughing a Java out of bounds exception..
latest 1.3.6 build, i will build a dev build and test to see if still happens..

`local args = {...}
local player_name = args[1]
local inv = peripheral.wrap("top")
inv = inv.getPlayerInv(player_name)
local size = tonumber(inv.getSize())
local start_items = {}
for i=1, size do
  start_items[i] = inv.getStackInSlot(i)
end`
