### ISSUE TITLE
player interface slots permcard-only

### ISSUE THREAD

**Issue by alandoyle95** [austinv11/PeripheralsPlusPlus#129]
noticed a commit where it said this was fixed.. so wanted to report that it's not.
![e69b9e841cf3f7dee542baff11d170ce](https://cloud.githubusercontent.com/assets/6220497/10325868/09bdf406-6c4a-11e5-93f8-15bcf31c1de4.png)

**Comment by grandmind** [comment]
Confirmed, only when shift-clicking. (transferStackInSlot())
