### ISSUE TITLE
Rocket sound server crash

### ISSUE THREAD

**Issue by LoganKaser** [austinv11/PeripheralsPlusPlus#13]
Server crashes on rocket place event.
though from your file comments it looks like you know the rocket sounds are broken.
Error log: http://pastebin.com/Xm5wqcqn

**Comment by austinv11** [comment]
Thanks for the report! Do you have a crash report by any chance?

**Comment by LoganKaser** [comment]
http://pastebin.com/Xm5wqcqn

**Comment by LoganKaser** [comment]
Nice!, can't wait for the working system. I have a super complex routing system setup but it's too slow for file transfers, can't wait for the satellites!
