### ISSUE TITLE
Me Bridge function edit suggestion

### ISSUE THREAD

**Issue by alandoyle95** [austinv11/PeripheralsPlusPlus#133]
it would be nice to have 

listItems(),
listCraft(),
listAll()

return the ItemID along with the other info it returns so that there is a way to get an ItemID from its name inside a program, it already returns the Meta for the items so unless there was a reason itemID was no implemented that im not aware of i think that this would be an amazing addition to the returned data :)

**Comment by grandmind** [comment]
I'm sorry, I'm not sure what you mean. I'm not sure about listItems() and listCraft(), but I know that listAll() already includes the ID of the item. Am I misunderstanding?

**Comment by alandoyle95** [comment]
this was related to the whole item name being the ID thing...
