### ISSUE TITLE
Me bridge retrieve() and craft()

### ISSUE THREAD

**Issue by alandoyle95** [austinv11/PeripheralsPlusPlus#134]
off the docs (http://peripheralsplusplus.readthedocs.org/en/latest/peripherals/me_bridge/)

retrieve(string itemId, number amount, string or number directionToDeposit)
craft(string itemId, number amount)

trying to run this..

![563251522b8248945598c2dbb7d69936](https://cloud.githubusercontent.com/assets/6220497/10392341/f44bf080-6e3a-11e5-8d19-7f59dd2e4bfd.png)
OR
![4fa8cc2471487b38add8b8e7d250afc7](https://cloud.githubusercontent.com/assets/6220497/10392390/7cfe1552-6e3b-11e5-98d1-4276ba726ca1.png)
causes...
![6a934972eb937e89b626f598d5ab347d](https://cloud.githubusercontent.com/assets/6220497/10392327/de6aaa0e-6e3a-11e5-8346-910ec2c7630c.png)

**Comment by grandmind** [comment]
You're passing "4" and "5" as the id rather than "minecraft:cobblestone" or "minecraft:planks"

**Comment by alandoyle95** [comment]
oh. well would that not be the items real name and not the ID then?
because when you do the listAll function it returns that as the items name and not the id.
so that could be misleading..

![6078941801a696c8e8980478690c9129](https://cloud.githubusercontent.com/assets/6220497/10413391/ee52fe5e-6f5b-11e5-8871-ea41b8fd9b23.png)

**Comment by grandmind** [comment]
Mojang abstracted item ids a while ago. The ID, on the outermost level, is no longer a number, but a string like "minecraft:stone"

**Comment by alandoyle95** [comment]
ok, now that makes sense

**Comment by grandmind** [comment]
But you are right, that could be misleading. I'll change it to say ID instead.

**Comment by alandoyle95** [comment]
:+1:
