### ISSUE TITLE
ME bridge listing items being weird

### ISSUE THREAD

**Issue by alandoyle95** [austinv11/PeripheralsPlusPlus#135]
ok so basicly..
listAll() works fine
listItems() returns 0
listCraft() returns fine

here is the rundown of how i tested it with 2 diffrent ME networks and tried restarting the server as well.

the crafting recipe is wood planks

the listItems should return 3 because there are wood planks in there..

Items
![0dcc9d800c0c52776b1b980139a44d1a](https://cloud.githubusercontent.com/assets/6220497/10416810/a53dd1e2-6fda-11e5-99f1-d48edf97790e.png)

Code
![5257d9f371437e404ad8067f56a4be73](https://cloud.githubusercontent.com/assets/6220497/10416809/a17a1e26-6fda-11e5-8b81-10d9347365a4.png)

Result
![3a7b216e593c76d5b56082e9e3b50c45](https://cloud.githubusercontent.com/assets/6220497/10416811/b2d1f702-6fda-11e5-9bf2-8b5af08903b2.png)

**Comment by Muramasa-** [comment]
listItems() has always just not worked.

You are ok to use listAll() as it should be doing the same as listItems() but listing all items in all referenced locations. So that could be chests connected to storage buses etc.
