### ISSUE TITLE
Crash while trying to look at some recipes in NEI

### ISSUE THREAD

**Issue by AlexPlus117** [austinv11/PeripheralsPlusPlus#136]
Everytime I try to look at some recipes in NEI like Chemical Turtles, my client crashes: http://pastebin.com/aF5bWUYr

**Comment by DJPantheris** [comment]
The stacktrace says that the crash in question started with the Java VM thread:
at com.austinv11.peripheralsplusplus.nei.TurtleRecipeHandler.loadCraftingRecipes(TurtleRecipeHandler.java:72)
