### ISSUE TITLE
RF turtle charger not enabled with Railcraft or Buildcraft

### ISSUE THREAD

**Issue by LoganKaser** [austinv11/PeripheralsPlusPlus#14]
Railcraft and Buildcraft both use RF, I have no idea how/if the api is different but I would love to be able to use it with these mods. Some people even run power-converters and Might want the option.

**Comment by austinv11** [comment]
Oh right, should be trivial to implement

**Comment by LoganKaser** [comment]
Awesome!

**Comment by austinv11** [comment]
Closed for now, but so far, only Buildcraft is supported as of commit 4b8c81ff57bedaee79db8c01785f71a750ad4ce2
