### ISSUE TITLE
Chat Box between dimensions

### ISSUE THREAD

**Issue by juniorjunior** [austinv11/PeripheralsPlusPlus#141]
Even when the config is set to infinite distance, the chat messages (both tell and say) do not show up for players outside of the dimension where the Chat Box resides.

**Comment by juniorjunior** [comment]
I just built from the c1a2cf3 commit and tested it in SSP. The commands continue to work as expected but I still receive no cross-dimension tells.

**Comment by grandmind** [comment]
I forgot about tell. I'll fix that today. Also, there's no need to build it yourself, you can download dev builds from Austin's CI server.
https://drone.io/github.com/austinv11/PeripheralsPlusPlus
