### ISSUE TITLE
Placing an ME Bridge crashes the server

### ISSUE THREAD

**Issue by juniorjunior** [austinv11/PeripheralsPlusPlus#143]
When I place an ME bridge, even when not side adjacent to any other machines/blocks (except cobble), I get this crash: http://pastebin.com/274qq496

**Comment by grandmind** [comment]
You didn't include the full crash report but I'm guessing you're using an alpha version of AE2.

**Comment by juniorjunior** [comment]
Full report: http://pastebin.com/kVePzXqW

But, no. I'm using the current beta of AE2rv3.

**Comment by grandmind** [comment]
Oh, I didn't know it was in beta as well. AE2 changed their API past the most recent stable version. This is becoming more of an issue, so I'm going to make a development branch you can use for unstable versions of AE2.

**Comment by juniorjunior** [comment]
Most excellent.

**Comment by grandmind** [comment]
https://github.com/austinv11/PeripheralsPlusPlus/releases/tag/v1.3.5-dev

**Comment by MJRLegends** [comment]
@GrandPanda any chance we can get regular version for AE2rv3, i.e v1.3.6
