### ISSUE TITLE
Debug spam in console

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#144]
When someone place PlayerDetector, console is spammed by range.

I found System.out.println(range); on line 85 at TileEntityPlayerSensor.java

That's little bit problem, so I hope someone will delete it ASAP.

**Comment by ArcasCZ** [comment]
There are more debugs with range, search for ussage LOGGER.info(range) ;)

**Comment by grandmind** [comment]
Ah ok sorry. I tried to just do a quick edit on mobile. I won't be at a computer for a couple more hours.

**Comment by ArcasCZ** [comment]
https://github.com/austinv11/PeripheralsPlusPlus/blob/dcea9351935e30ec9314ec795034802499b776e8/src/main/java/com/austinv11/peripheralsplusplus/utils/ChatUtil.java#L20

Here is another debug. I think that's all but I'm not sure...
