### ISSUE TITLE
Chatbox and events

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#145]
ChatBox doesn't ignore cancelled chat events -_-

**Comment by ArcasCZ** [comment]
Compiled, updated and nope - ChatBox still reacts to muted messages -_-

**Comment by grandmind** [comment]
Oops, try that.

**Comment by ArcasCZ** [comment]
I'm so sorry, but it still seems not working :D I gave myself mute, then I write ,,Hello" and text appeared on screen... -_- :D

**Comment by grandmind** [comment]
How are you "muting" yourself? It may be a problem with how that is being handled.

**Comment by ArcasCZ** [comment]
Maybe I should tell you I'm running KCauldron and muting is equal to event.setCancelled(true) in Bukkit API :D

**Comment by ArcasCZ** [comment]
FInally - problem is not on our side. It's bug in KCauldron code - missing Bukkit event cancel check -_- Now it's on Prototik to fix it :-)
