### ISSUE TITLE
Player Interface not working

### ISSUE THREAD

**Issue by Nathan1852** [austinv11/PeripheralsPlusPlus#150]
The Player Interface doesn't seem to work. retrieveFromSlot does just nothing (and returns nothing)
and getStackInSlot doesn't return anything for the first 1000 Slots, even if I have multiples Items in my inventory

**Comment by grandmind** [comment]
I was unable to reproduce this in any way. What do you mean the first 1000 slots? The player inventory only has 40.

**Comment by Nathan1852** [comment]
I did a for loop from 1 to 1000, calling getStackInSlot for each number, thinking that I probably used the wrong slot numbers at first. But getStackInSlot never returned anything, even with more than enough Items in my Inventory

**Comment by grandmind** [comment]
Ok, well, like I said, I was completely unable to reproduce this. It seems to work fine. Unless you can provide any more information, I'm going to close this for now.
