### ISSUE TITLE
Thirsty Turtle bug

### ISSUE THREAD

**Issue by JacWa** [austinv11/PeripheralsPlusPlus#151]
Using the pack() command with an empty bucket in the selected slot on a thirsty turtle seems to make the bucket into an infinite water source: [https://gyazo.com/f538c9199ce03591a87e04fefb1267a9](url) This affects all empty buckets created before and after doing this, and I haven't found a way of fixing it without creating a new world. 

I came across this bug whilst trying to get the thirsty turtle to deposit water into an openblocks tank that has been placed in the world, don't know if there is a way to get that to work either or if it needs to be fixed too?

**Comment by grandmind** [comment]
Quick update: I decided to completely rewrite the thirsty turtle as there were too many problems with it to just fix this one. It should be done in the next few days, but school might get in the way. In the mean time, restarting the game / server should fix the buckets.

**Comment by grandmind** [comment]
Alright, it's mostly done. It's missing a few things, but I thought this was better than the broken mess it was before. I'll give you a quick rundown of what's changed so you can use it better:

- pack() and unpack() were renamed to fill() and drain() respectively 
- place() was renamed to empty()
- Too many bugs to count fixed
- Should function with all Forge Fluids if their parent mod registers them properly

**Comment by JacWa** [comment]
Thanks a bunch!
