### ISSUE TITLE
ME Bridge - Argument Bug

### ISSUE THREAD

**Issue by Muramasa-** [austinv11/PeripheralsPlusPlus#159]
So it has taken me a solid 30mins to figure out why I couldn't pass metadata to the retrieve method.

This is what I expected it to be:
me.retrieve(tbl[lastIndex]["name"]..":"..tbl[lastIndex]["meta"], fixedItemNum, "up")

However the first argument requires a space in between the colon and the metadata string like this:
me.retrieve(tbl[lastIndex]["name"].._**": "**_..tbl[lastIndex]["meta"], fixedItemNum, "up")

From looking at the code it seems to be because of the extra split at the end of this line https://github.com/austinv11/PeripheralsPlusPlus/blob/master/src/main/java/com/austinv11/peripheralsplusplus/tiles/TileEntityMEBridge.java#l117

**Comment by rolandoislas** [comment]
The ME Bridge expects to parse the following format: `modId:itemName metaData`, with metaDataBeing optional. For a vanilla item, the modId is "minecraft".

**Comment by Muramasa-** [comment]
Oh my mistake. I swear it was differently previously. Anyway thanks for clearing that up.
