### ISSUE TITLE
Config file suggestion!

### ISSUE THREAD

**Issue by MJRLegends** [austinv11/PeripheralsPlusPlus#165]
Please make to so when you set the enabled part in the config for blocks it actually removes the blocks not just the recipe or make a way to or just recipes and then one for both recipes and remove the block.....

**Comment by MJRLegends** [comment]
@austinv11 any thoughts on this

**Comment by GrandPanda** [comment]
This project is no longer maintained. The chances of austin implementing this (or any other features) are extremely low. That being said, if you really need a change like this, you can fork and add it yourself.
