### ISSUE TITLE
[Feature Request] GPS Module

### ISSUE THREAD

**Issue by NPException42** [austinv11/PeripheralsPlusPlus#17]
Could you make some kind of GPS Module as a Turtle peripheral, so that the Turtle can use something like this?

```lua
local gps = peripheral.wrap("left")
local x,y,z = gps.getPosition()
```

One thing that I always found nearly impossible to do, was to get a turtles position for continuing a program after a chunk unloaded and reloaded. Using Rednet for GPS is pretty much not an option if you want a turtle to move over a large area or just want to place it down and fire it up.

The GPS Module should be reasonably expensive IMO, since it is a pretty nice thing to have.
Maybe it could be upgrade from the Compass module. :)

Thanks for reading o/

**Comment by austinv11** [comment]
I will close this for now because I have a system in mind (it involves satellites :D), expect it soon(tm)

**Comment by NPException42** [comment]
You had my curiosity,
but now you have my attention. :D
