### ISSUE TITLE
Crash with Cauldron

### ISSUE THREAD

**Issue by kimfy** [austinv11/PeripheralsPlusPlus#18]
Hello.

Whenever I try starting my server using Cauldron 1236 it crashes on me. I've tried launching the server without Cauldron and that works fine.
I really hope you manage to fix this(if it's on your end) because I love this mod and I really want it on my server. Thank you.
My crash log is here: http://pastebin.com/fJ9FpkTK

EDIT: I just read http://www.computercraft.info/forums2/index.php?/topic/20903-mc-1710cc-165-peripherals-v120beta4-miscperipherals-reimagined-now-includes-speakers/page__view__findpost__p__203322 and I understand this can't be fixed. This really sucks... Oh well.

**Comment by austinv11** [comment]
I'll take another look at this, but I can't guarantee that it'll be fixed.
