### ISSUE TITLE
Server side 'mount'ed programs generating twice in different folders

### ISSUE THREAD

**Issue by JackBarnett2014** [austinv11/PeripheralsPlusPlus#20]
When installing P++ onto my dedicated server, the mounted programs seem to generating twice. Once in /null/mods/ppp_mount and /mods/ppp_mount/

<em><b>Specific OS + Java Version:</b></em>
Debian 7 (Wheezy)
Java 1.7.0_65 (Iced Tea 2.5.3)

**Comment by austinv11** [comment]
Fixed already
