### ISSUE TITLE
Rocket/Sattilite?

### ISSUE THREAD

**Issue by MrabEzreb** [austinv11/PeripheralsPlusPlus#22]
What do these do? Add it to the wiki!

**Comment by grandmind** [comment]
If I remember correctly, they don't really do anything at the moment. They are experimental and not functional yet.

**Comment by MrabEzreb** [comment]
:( if I could make a suggestion, make the rocket able to carry turtles, then let it work with galacticraft. THAT would be cool.

**Comment by austinv11** [comment]
Yeah, these are currently WIP. While your turtle idea sounds neat, that is currently impossible with the way the CC API works. It is also a bit unnecessary considering you could just carry turtles in your inventory.

**Comment by MrabEzreb** [comment]
ya, but what if you wanted to journey there with a probe first?

**Comment by grandmind** [comment]
So you want a GC expansion that allows for probes... This is a computercraft addon.

**Comment by Rieu** [comment]
Are the satellites still experimental? I only ask as there are no upgrades for them listed. Also how do I access the programs for antenna usage?

**Comment by Fxzy** [comment]
Yes, satellites are still experimental so there are no programs for them yet. But to get the other programs for the antenna, type "cd ppp", then "cd antenna" and if you type in "dir" you should see all the mounted programs.
