### ISSUE TITLE
Using Git

### ISSUE THREAD

**Issue by Cyb3rWarri0r8** [austinv11/PeripheralsPlusPlus#29]
You should really break up every version that you start working on into branches then once your done with that version merge it into master. Just a suggestion.

**Comment by austinv11** [comment]
Yeah I recently realized this, but I'm waaaaay too far into this update to start right now. Expect it after I publish this update

**Comment by Cyb3rWarri0r8** [comment]
Okay. I gotcha. Some one of my other mods I haven't used the branches just because I haven't done enough work on them.
