### ISSUE TITLE
Smart helmet doesn't work

### ISSUE THREAD

**Issue by jilleJr** [austinv11/PeripheralsPlusPlus#32]
I am trying to use the smart helmet but it doesn't draw anything on my screen.

I tried using the `helmet` program that comes with the mod (the Dynamic Mount so to speak) by @Fxzy (says Fxz_y in the code) but the only thing that worked on there was the print resolution option. I played around a bit more and found that it simply can't draw for some reason. Super strange.

This is the program I tested and it doesn't do anything noticeable, while it should make a big red bar at the top right?
```lua
p = peripheral.find("antenna")
hud = p.getHUD(p.getPlayers()[1])

w,h = hud.getResolution()

color = hud.getColorFromRGB(255,0,0)
hud.drawRectangle(0, 0, w, 200, color)

hud.sync()
```

**Comment by grandmind** [comment]
I was able to get this functioning using your provided code. 
Two things before I go into trying to track down the problem:
1. Are you sure the helmet and the antenna you're using are linked? To link them, you must right click on the antenna with the helmet in hand.
2. Are you wearing the linked helmet?

**Comment by Fxzy** [comment]
@jilleJr While bugtesting the smart helmet we have stumbled upon some problems relating to forge.
Mind telling what version of forge you are running?

**Comment by Fxzy** [comment]
@grandmind Don't bother going through the code, you won't find anything :smile:

**Comment by jilleJr** [comment]
@grandmind the code worked without any errors. I made sure to link up the antenna and helmet, I even labeled the antenna before linking. I did this in a creative singleplayer world so no other players could be interfearing. Am I missing something? I used an advanced computer and the antenna peripheral, nothing else (except for the helmet of course)

**Comment by grandmind** [comment]
Alright. As @Fxzy asked, what forge version are you currently using?

**Comment by jilleJr** [comment]
@grandmind @Fxzy I am using the following:

Minecraft 1.7.10
**Forge 10.13.2.1291**
ComputerCraft 1.73
OpenModsLib 1.7.10-0.6
OpenPeripheral 1.7.10-AIO-1
**Peripherals++ 1.2.0**
Pneumaticcraft 1.7.10-1.5.3

**Comment by jilleJr** [comment]
Just for testing I disabled all mods except peripherals++ and computercraft, and it still doesn't work.

**Comment by Fxzy** [comment]
@jilleJr, @austinv11 is releasing an update that might fix the issue, if it still persists, please tell us.

**Comment by jilleJr** [comment]
@Fxzy Ok when will this new build be available and where can I find it?

**Comment by austinv11** [comment]
I just released v1.2.1, [here](https://github.com/austinv11/PeripheralsPlusPlus/releases/download/v1.2.1/Peripherals.-1.2.1.jar) is a direct link to the download. Please report back if it doesn't work.

**Comment by jilleJr** [comment]
@austinv11 Nope still doesn't work.

**Comment by jilleJr** [comment]
Just tested it with another IRL computer and it still *doesn't* work...

**Comment by austinv11** [comment]
This is in single player right?

**Comment by austinv11** [comment]
Okay, I know what's wrong. It doesn't work in creative for some reason. Fixing now

**Comment by jilleJr** [comment]
Oh I see, I never tested it in survival mode. Good job finding it! :)
