### ISSUE TITLE
Using getNearbyPlayers throws a Java Exception

### ISSUE THREAD

**Issue by dakotaaesoph** [austinv11/PeripheralsPlusPlus#36]
I wrote in the Interactive Lua Prompt on a Turtle **peripheral.wrap("right").getNearbyPlayers(20)** and it says Java Exception Thrown.

**Comment by Fxzy** [comment]
We can't reproduce this, we've tried using the turtle with the upgrade on both sides and we've tried just the computer with the peripheral block next to it and it worked perfectly in all cases.

Mind telling us the mods you used when this problem occured? So we could investigate more.

**Comment by dakotaaesoph** [comment]
Did you try it on Multiplayer? Because I'm only able to replicate it on Multiplayer. I only have ComputerCraft 1.65 and Peripherals++ 1.3.0-71 installed.

**Comment by dakotaaesoph** [comment]
I updated ComputerCraft to 1.73 and it's says Java Exception Thrown: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.func_70666_h(F)Lnet/minecraft/util/Vec3;

**Comment by Fxzy** [comment]
Confirmed, Java exception thrown when using on a server.

**Comment by Fxzy** [comment]
Can you please upload the full FML log? You can find it under (instance name)/minecraft/logs/
Search for the latest, upload it on pastebin and post the link here please.

**Comment by dakotaaesoph** [comment]
It's too big for Pastebin. 512kb limit.

**Comment by austinv11** [comment]
Yeah, I know what's wrong. I will release an update in around 10-20 minutes
