### ISSUE TITLE
Smart helmet hud.getResolution()

### ISSUE THREAD

**Issue by jilleJr** [austinv11/PeripheralsPlusPlus#38]
This is a minor bug.
The `hud.getResolution()` function returns the resolution from the small GUI scale.
Would be nice to either get the resolution depending on GUI scale or get a `hud.getGUIScale()` function. (Or even have the GUI scale be a third variable to return from `hud.getResolution()`).

And in the case of getting the GUI scale I then mean a number, like 50% of the resolution.

Last option could also be to ignore the GUI scale and have it draw smaller anyways, but that wouldn't be a good solution *imo*.

**Comment by grandmind** [comment]
You're correct, the method is supposed to return corresponding with the player's GUI scale.

**Comment by austinv11** [comment]
I think I'll just add a method called getScaledResolution() to return the resolution with the gui scale in mind.
