### ISSUE TITLE
Chatbox pickup messages from custom NPCs

### ISSUE THREAD

**Issue by jilleJr** [austinv11/PeripheralsPlusPlus#39]
I was just watching Etho's modded episode (https://youtu.be/T3fceIoQsE4) where he introduced Peripherals++ to his series, and he had this idea that the custom NPCs you can make with the Custom NPCs mod should be able to communicate with computercraft via the chat.

If you're not familiar with custom NPCs then it's a mod that lets you make custom NPCs (surprise surprise) but also lets you script them, like entity turtles.

Would be cool if you could tap into the NPCs API (if they have one) and have the ChatBox listen to their chat messages as well.

Link to Custom NPCs: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs

**Comment by grandmind** [comment]
Hey, I agree that this would be a very cool feature. However, the lack of functionality there is most likely a problem on CustomNPC's side. The chatbox listens for <b>all</b> chat events. If the chatbox is not picking up on CustomNPC's messages, then it is not being done in a conventional way with an event being fired. I was also unable to find source code or an API for the mod, so you'll have to take it over to them.

**Comment by austinv11** [comment]
I have just released a tweak mod to fix this, download it here: http://minecraft.curseforge.com/mc-mods/229901-customnpc-tweaks

**Comment by Selim042** [comment]
Oh, I had sent Noppes a message about that, and got a custom version from him that fixes that now...

**Comment by grandmind** [comment]
Are you sure about that? Last release was a week ago and for 1.8...
http://minecraft.curseforge.com/mc-mods/221826-custom-npcs/files

**Comment by Noppes** [comment]
He was too hasty
http://minecraft.curseforge.com/mc-mods/221826-custom-npcs/files/2235567

**Comment by austinv11** [comment]
Thanks Noppes! Glad you added that.

**Comment by Selim042** [comment]
At the time, the one he sent me was version d, so when I looked on the CurseForge, I saw version d, and didn't look at release date.  Glad its up there now though.
