### ISSUE TITLE
Server crash when deleting worlds with Multiverse

### ISSUE THREAD

**Issue by kimfy** [austinv11/PeripheralsPlusPlus#43]
Hello. When deleting/removing/unloading a world with Multiverse it crashes my server. Here's a [pastebin](http://pastebin.com/hRJK4kya). I tried disabling Satellites in the config but it doesn't remove it completely I guess. Let me know if this is a Multiverse issue, I'm reporting it here because my crash doesn't mention Multiverse at all.

**Comment by austinv11** [comment]
Sorry, but bukkit is not known to play nice with forge, I may revisit this in the future however.
