### ISSUE TITLE
Chatbox issues

### ISSUE THREAD

**Issue by MarcuzD** [austinv11/PeripheralsPlusPlus#46]
I have a problem with the chatbox:
When I call chat.tell("ply", "msg"), I get a java exception about the mod didn't found the "Vec3 func_70666()" function in EntityPlayer. This only happens on the server-side.

I'm using the 1.2.7 version of the mod on Minecraft 1.7.10 with Forge #1291 running in Java 1.8.0-ea-b120 (Java8)

**Comment by grandmind** [comment]
We need a log to help you.

**Comment by MarcuzD** [comment]
There is nothing, the server console is "empty", there's nothing on the client side (why would there be?), the logs are "empty", the only thing I see is this (image of the computer)[http://puu.sh/h7KSs/12f5068774.jpg]. The server log is too big to be sent, and there are no initialization errors, nor anything about malfunction. It looks like it's caused by CC, or even LuaJ, that  caught exceptions are not .printStackTrace()'d. I think that the exception is thrown at com/austinv11/peripheralsplusplus/utils/ChatUtil.java at line 43, where it makes a call to player.getPosition. I think this may be caused of some weird (de)obfucation issues. This may be a bug in Forge, so I'll update, and report the progress.

**Comment by MarcuzD** [comment]
There is nothing, the server console is "empty", there's nothing on the client side (why would there be?), the logs are "empty", the only thing I see is this (image of the computer)[http://puu.sh/h7KSs/12f5068774.jpg]. The server log is too big to be sent, and there are no initialization errors, nor anything about malfunction. It looks like it's caused by CC, or even LuaJ, that  caught exceptions are not .printStackTrace()'d. I think that the exception is thrown at com/austinv11/peripheralsplusplus/utils/ChatUtil.java at line 43, where it makes a call to player.getPosition. I think this may be caused of some weird (de)obfucation issues. This may be a bug in Forge, so I'll update, and report the progress.

**Comment by MarcuzD** [comment]
Nope, it's the same for Forge #1360

**Comment by grandmind** [comment]
Sorry, I misread your original message. Austin has identified the issue and will be working on it.
