### ISSUE TITLE
Ore Dictionary breaks when an item has 2 oreDict entries.

### ISSUE THREAD

**Issue by Fxzy** [austinv11/PeripheralsPlusPlus#5]
Title says it all. The title is multifunctional.

**Comment by rolandoislas** [comment]
Tested with colored glass pane (Minecraft) and ender dust (AE2). Peripheral seems to be working as intended.

**Comment by austinv11** [comment]
I'm gonna close this for now.

**Comment by grandmind** [comment]
I only ever tested it with woods. Not sure if it's still an issue.
