### ISSUE TITLE
ME Bridge stops work with modded items

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#50]
Hello there!

First i want to apologize for my bad English - I'm from Czech.

I had a big problem. My friend AEdison wrote a complex program for my server. It works like real casino. Everythink is good, but when he want's to move modded items from ME to chest, function returns 0. But when he want move vanilla items, all works. If you need more informations, ask me here. Or we can meet on my TeamSpeak server.

Greetings
ArcasCZ

**Comment by ArcasCZ** [comment]
Can I ask you? How long it will spend untill you push new version? I tried to compile it myself by NetBeans, but I'm too noobish to complete it...

**Comment by austinv11** [comment]
Expect it around 4-5pm EST. I would do it now but I have school :/ Just note that the fix allows you to put metadata. So orange wool would be "minecraft:wool 1".

**Comment by ArcasCZ** [comment]
No problem man, I'm at school too. If you can push it before 6pm I'll be happy, 'cause at Europe It will be about 12 pm ;)
