### ISSUE TITLE
ChatBox listens to server /say

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#52]
Hello there.

I think chatbox is missing one feature - listening to server's messages. That suggestion came from my friend when we were making CC casino. If ChatBox listens to /say output messages, we can handle restart announcement, stop players from playing 5 minutes before restart and close casino.

**Comment by austinv11** [comment]
The problem is that this is due to the way vanilla handles the /say command. I will fix this, but this requires coremodding so I will fix this in my coremod. My coremod is not yet publicly available, but if you wish I can give you an early download.

**Comment by ArcasCZ** [comment]
If it won't be buggy i agree - it's a great opurtnity for my friend and me. And can i ask you - how looks update to 1.2.8 with fixed chatbox and ME bridge? :-)

**Comment by Selim042** [comment]
And, the rid-able Turtles :)

**Comment by austinv11** [comment]
Here https://drone.io/github.com/austinv11/PeripheralsPlusPlus/files. It will be a little bit before I am able to post it to curseforge. But that contains all the fixes (no new features though, that's for version 1.3 ;))

**Comment by Selim042** [comment]
Do you have an ETA on 3.0 then?  Really want some of those Turtles :)

**Comment by ArcasCZ** [comment]
Austin? If you have little time on weekend, we can meet on TeamSpeak and i can show you how AEdison's codes works. It's great opurtnity to get new ideas ;)

**Comment by austinv11** [comment]
Here you go: https://drone.io/github.com/austinv11/CollectiveFramework/files. Remember, it's still early in development so if there are bugs let me know, [here's the github repo for it](https://github.com/austinv11/CollectiveFramework).

**Comment by ArcasCZ** [comment]
And where i can get latest version of PPP with CF support?

**Comment by grandmind** [comment]
The latest version can be downloaded here: https://drone.io/github.com/austinv11/PeripheralsPlusPlus/files

**Comment by ArcasCZ** [comment]
There's no build...

**Comment by austinv11** [comment]
I am currently having a problem with the build script, just download the version on curseforge currently. The tweak I added to CF is compatible with that build
