### ISSUE TITLE
Real time

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#53]
Hello there!

I'm back with new issue.

In our CC casino we have CC server, that response to slot machines request about jackpot. That server solves every jackpot thing - add items to jackpot, generate jackpot, payout jackpot... But if we want to log every acess on server with time, we have to use AEdison's function, that returns timestamp. That function get timestamp at our web. But sometimes this function has 0.4 ms response time. Thats too much. If server waits for time to log, in this time teoreticaly can get 5 request about jackpot and due to this wait time, 5 slot machines can't get information about jackpot and generates only common wins. What we need is some function that allow you get unix timestamp from java server. That's all.

If you want to look at sourcecode of AEdison rtime funciton, here is: http://pastebin.com/XDjBMX3z

**Comment by Selim042** [comment]
I second this ^

**Comment by grandmind** [comment]
There you go! :D

**Comment by ArcasCZ** [comment]
That function returns UNIX time or formated time?

**Comment by grandmind** [comment]
It returns the time formatted, but I can add a function for just unix time if you'd like, though.

**Comment by ArcasCZ** [comment]
It will be good if you can. And can you return formated time in array? Like that: http://pastebin.com/AzciqsbA
