### ISSUE TITLE
[Bug] Client/Server Console Log + SMP Rocket Crash

### ISSUE THREAD

**Issue by lurquhar1221** [austinv11/PeripheralsPlusPlus#55]
Currently, there is a large issue I have found while running my server.
The console reads: "5.0", over and over (approx. 25 times per second). This lags the server, and affects me, a server owner, by spamming the console to the point where it's unreadable.

For the SMP Rocket crash, when you place a rocket, the server crashes instantly. Looking through the tracelog, I can verify that the mod is attempting create an instance of an Audio file on the server. (a.k.a. Audio in wrong Proxy, put in client, not common).

When running this in singleplayer however, the problem is non-existent, however, it still spams the console

I hope this helps the mod and other people with this same issue.

**Comment by grandmind** [comment]
Hi, the actual crash report is necesaary to help you. Please also make sure that you are running the latest version. That "5.0" issue might be leftover debugging info from an old version of the mod. Also please note that the rocket is very clearly marked as WIP and is disabled by default.

**Comment by austinv11** [comment]
Gonna close this. If there are still is still an issue, let me know
