### ISSUE TITLE
Turtle FakePlayer

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#57]
Is there some way how you can fix orignal CC FakePlayer? We have some problems with turtles going into residence...

**Comment by grandmind** [comment]
Sorry, I don't really understand your problem. Could you explain it a bit more?

**Comment by ArcasCZ** [comment]
If turtle dig a block, it dont fire an event to plugins, so i can handle it with Residence and in case of griefing someone's house i can't cancel event and turtle don't register it.

**Comment by austinv11** [comment]
Yeah, I don't think I could fix that.
