### ISSUE TITLE
ME Bridge and network with Security Terminal

### ISSUE THREAD

**Issue by Andreiovitch** [austinv11/PeripheralsPlusPlus#58]
Hello,

First, this is an awesome mod and I'm really glad somebody has brought back MiscPeripherals—and even better!

Second, I've noticed that if I have an ME Security Terminal from AE2 connected to the same network as the ME Bridge peripheral, both retrieve() and craft() methods return "Java Exception Thrown: java.lang.ClassCastException". When I remove the Security Terminal, the methods work as expected. (listAll(), listItems(), and listCraft() work in both instances). AE2 requires you to have the security terminal connected in order to use the wireless terminal (I think), so this potentially renders the peripheral useless if one likes to use the wireless terminal.

Thank you!

Andreiovitch

**Comment by Andreiovitch** [comment]
Also, versions are: PPP 1.2.8, AE2 rv2 beta 29.

**Comment by austinv11** [comment]
Hm, I'll look into it
