### ISSUE TITLE
TODO for 1.2.0

### ISSUE THREAD

**Issue by austinv11** [austinv11/PeripheralsPlusPlus#6]
* Finish rocket and satellite system
* ~~Add built-in programs~~
* ???
* Profit!

**Comment by NPException42** [comment]
I have a suggestion: Consider switching over from IEnergyHandler to IEnergyReceiver for the RF Turtle charger, since IEnergyHandler will get removed in future versions of the RF API.
https://github.com/austinv11/PeripheralsPlusPlus/blob/master/src/api/java/cofh/api/energy/IEnergyHandler.java#L15

**Comment by austinv11** [comment]
Thanks for letting me know, will do!
