### ISSUE TITLE
[Suggestion] Player Interface

### ISSUE THREAD

**Issue by Pyeroh** [austinv11/PeripheralsPlusPlus#62]
Apparently it hasn't been suggested yet, so I do it : OpenPeripherals add a Player Interface to allow modification of player inventory. Could it be added to PPP ? Because I think your mod offers more content than OpenPeripheral do, and I don't like to add mods that do almost the same thing...

In case you don't know it (or for anyone who come here), the PIM allow to edit player inventory who stands on it. A wiki page about it : http://ftbwiki.org/PIM

**Comment by Selim042** [comment]
Personally, I think there should be a wireless version of the PIM.

**Comment by Pyeroh** [comment]
Yeah, sure, like the player sensor do : target a player, then do changes on him.

**Comment by austinv11** [comment]
Sounds cool, but before it's implemented, I'll need to figure out a way to not make it OP. As griefers could use it to steal straight out of someone's inventory.

**Comment by Selim042** [comment]
Whoever places it is the player it interacts with?

**Comment by austinv11** [comment]
Then there would be limitations as to what you could do with it

**Comment by Selim042** [comment]
I can't think of another good way (right now) to limit editing to players that give the user permission.

**Comment by Pyeroh** [comment]
But in a permission context, you have to give permissions to a fake player. And generally, a fake player (computer, machine, etc.) has almost every permissions.

**Comment by rolandoislas** [comment]
I think having something similar to the AE2 biometric cards would help with the security issues. It would make it so the machine can only interact with the inventories of players that have willingly inserted the biometric card imprinted with their data. Another thought would be having a GUI where a player can allow the device to interact with their inventory.

**Comment by austinv11** [comment]
Yeah, I was thinking something along those lines.

**Comment by Selim042** [comment]
The ideas for uses of these are already flowing :)

**Comment by austinv11** [comment]
We have just added it :)

**Comment by Selim042** [comment]
YAY!

**Comment by Pyeroh** [comment]
Yeah ! Thanks a lot, this mod is getting more and more awesome :D
