### ISSUE TITLE
RealTime Format

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#66]
Can you please add function for unix time and formate time return in array (like that - http://pastebin.com/AzciqsbA)? :-)

**Comment by rolandoislas** [comment]
The wiki needs updating,  but the getTime method return a Unix timestamp in milliseconds (divide by one thousand for seconds). There is also a getDate method which returns a table with the year, month, minutes, etc.

**Comment by austinv11** [comment]
Yeah, the wiki is outdated and its getting sort of annoying to manage. I am currently looking for a new platform to host it on as well as rewriting large portions of it

**Comment by ArcasCZ** [comment]
Where i can download it? :-)

**Comment by MrabEzreb** [comment]
ever heard of tiddlywiki?

**Comment by austinv11** [comment]
Download it here: https://drone.io/github.com/austinv11/PeripheralsPlusPlus/files

I was also planning in using ReadTheDocs, that way the documentation can be hosted on this repo and people could pull-request improvements if they wish
