### ISSUE TITLE
PPP still requires AE to run [latest version of PPP]

### ISSUE THREAD

**Issue by MFernflower** [austinv11/PeripheralsPlusPlus#70]
Removing AE from my modpack results in a crash from PPP *The config option does not appear to help*

**Comment by MFernflower** [comment]
http://pastebin.com/cWcLx6wc

**Comment by DrZed** [comment]
I kinda wanna open a new issue myself "[EMERGENCY] Code looks like a pile of vomit"

**Comment by austinv11** [comment]
You used 1.2.9, looks like curse took awhile to approve 1.2.10

**Comment by MFernflower** [comment]
Confirmed. Works well
