### ISSUE TITLE
Disable update detect

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#74]
Hi there!

I want to use new PPP for my brand new modpack. But i found that update notification is little unconfortable for me, 'cause i can't block it in config and if one of players click on update, they will have a big problem with launching game.

Modpack is still beta but i hope you will add some boolean to disable / enable update check ASAP.

Thanks.

**Comment by austinv11** [comment]
There is a config option for it, set "doVersionUpdateChecks" to false

**Comment by ArcasCZ** [comment]
I did it, but that doesn't seems to work...

**Comment by austinv11** [comment]
Fixed, download it here: https://drone.io/github.com/austinv11/PeripheralsPlusPlus/files
