### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#76]
http://pastebin.com/EWS0Eybn

Using KCauldron 1403.78 - Forge 1403, newest version of PPP + CF

**Comment by austinv11** [comment]
Disable enableButtonTimeChanging in the CollectiveFramework as a temporary fix. I'm currently working on a more permanent one.

**Comment by austinv11** [comment]
[This](https://drone.io/github.com/austinv11/CollectiveFramework/files/build/libs/CollectiveFramework-1.0.0-110.jar) version of CF fixes it
