### ISSUE TITLE
Version 1.3 and modpacks

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#78]
Hello! :-)

Do you think it's safe to use version 1.3 in public modpacks? I think there's a lot of good stuff and improvements, but it's still beta..

**Comment by Fxzy** [comment]
I would suggest waiting for it to come out of beta first, I can't say if there is anything that could possibly break a modpack or a world. If you do update it make sure to note that everyone should back up their worlds before updating.

**Comment by austinv11** [comment]
Yeah, I don't think it's a good idea to distribute the dev versions in modpacks. As it is still in development so things are subject to change at any time. That being said, you still *can* put it in your modpack, but don't be surprised if there are bugs
