### ISSUE TITLE
Exception thrown when calling "tell" from Chatbox

### ISSUE THREAD

**Issue by Pyeroh** [austinv11/PeripheralsPlusPlus#80]
Here are details : 
When I try to call function "tell" from a chatbox, with all parameters, it yells that :
![2015-06-16_21 17 13](https://cloud.githubusercontent.com/assets/5567857/8180894/481a30d2-146d-11e5-8b5e-be508a0dadc9.png)
The whole command is
```
    p = peripheral.wrap("left")
    p.tell("Pyeroh", "MLP", 10, true, "Test")
```

I'm on a Chatty Turtle, but it happens also with a Chatbox and a computer.

**Comment by austinv11** [comment]
For now, you could fix it by not including the last argument

**Comment by Pyeroh** [comment]
Wow, such fix :dog2: 
By the way, it doesn't work : when I add this boolean, this exception is thrown...

**Comment by Pyeroh** [comment]
Thank you for your correction =)
