### ISSUE TITLE
Player detector event

### ISSUE THREAD

**Issue by ArcasCZ** [austinv11/PeripheralsPlusPlus#81]
Hello!

I want to ask you if you can add event, that will be called when someone come into player detector?

**Comment by austinv11** [comment]
There is already an event called when a player right clicks it

**Comment by ArcasCZ** [comment]
But we need fire event when player comes to the radius.

**Comment by grandmind** [comment]
Austin may still considering doing that, but that can already be done with the functionality that exists.

**Comment by austinv11** [comment]
You can simply run a loop in which you attempt to detect players and if you do detect a player: break the loop and do whatever you want to do.
