### ISSUE TITLE
Crash when launching with Peripherals++ 1.3.0 and latest Computercraft

### ISSUE THREAD

**Issue by abaw7** [austinv11/PeripheralsPlusPlus#83]
The client will crash during launch. Here's the report: http://pastebin.com/G0hGc8X1
Seems to be related to the pocket computer peripherals

**Comment by abaw7** [comment]
1.3.0 pulled from here: https://drone.io/github.com/austinv11/PeripheralsPlusPlus/files

**Comment by austinv11** [comment]
You need to also install Collective Framework, dev versions are available here: https://drone.io/github.com/austinv11/CollectiveFramework/files

**Comment by abaw7** [comment]
Tried all three jars just in case I was being stupid, all three failed. The crash reports are here:
CollectiveFramework-1.0.0-111.jar: http://pastebin.com/C5eQxZ2i
CollectiveFramework-1.0.0-111-source.jar: http://pastebin.com/kY82SC81
CollectiveFramework-1.0.0-111-deobf.jar: http://pastebin.com/a7VCVc7s

**Comment by austinv11** [comment]
You are supposed to use the CollectiveFramework-1.0.0-111.jar, but the crash with that is my fault
