### ISSUE TITLE
More Speaker TTS Stuff (Suggestion)

### ISSUE THREAD

**Issue by jjjhfam** [austinv11/PeripheralsPlusPlus#84]
I'm making a JARVIS sort of system but there doesn't seem to be a male with a British accent for the Speaker TTS. Maybe I'm not looking hard enough but it would be great if this was either added or clearer to find...

**Comment by grandmind** [comment]
The speaker uses google translate for TTS. Not sure if they have a male British voice, but there's not much austin can really do to add this as far as I know.

**Comment by jjjhfam** [comment]
I see. I've googled around quite a bit but never found anything. However, I did find a TTS website that said it used the Google TTS for its transcriptions into voice, with a language option "en-uk".

**Comment by austinv11** [comment]
Yeah, I can't change what voices are offered by Google, however I am working on adding a clientside synthesizer which will sound much more robotic
