### ISSUE TITLE
Comment on planned features

### ISSUE THREAD

**Issue by jilleJr** [austinv11/PeripheralsPlusPlus#87]
One of your planned features is as follows
- Easy-mode programmer block that ‘compiles’ code onto a floppy disk

And I was just curious if someone made this already and googled up CCEDU.
Have you seen CCEDU? It's mostly exactly what you describe.

Link to a small showoff by Dan200: https://twitter.com/DanTwoHundred/status/609858963715158017

If you feel like making your own that's fine but I just wanted to point it out if you felt like the feature was missing from the market.

This got me thinking tho, would be cool with a program like this but made in computercraft instead of a custom GUI

**Comment by austinv11** [comment]
Yeah, that's exactly what I was planning.
