### ISSUE TITLE
Nano Swarm

### ISSUE THREAD

**Issue by botaBG** [austinv11/PeripheralsPlusPlus#89]
Hi, I like your mod but I cant found Nano Swarm in NEI. Did they got remove or I am blind?
I am using Peripherals++-1.2.10

Edit:   http://imgur.com/rH5cmQH

**Comment by Nathan1852** [comment]
AFAIK they got added in 1.3.0, which isn't out yet. But there is an link to a beta version somewhere I think

**Comment by botaBG** [comment]
Thank you I will check later
