### ISSUE TITLE
Where is the chunck loader module from MiscPeripherals?

### ISSUE THREAD

**Issue by florensie** [austinv11/PeripheralsPlusPlus#90]
I really need this. I don't think there is any mod that supports this right now so this would be awesome.

**Comment by SquidDev** [comment]
I'm pretty sure [this one](http://www.computercraft.info/forums2/index.php?/topic/18156-mc-17-cc-173-chunky-peripherals-turtle-chunkloaders-mining-chunkloaders-crmod/) adds one. I haven't tried it myself but I'm pretty sure it works. Obviously having it in Peripherals++ would be great though!

**Comment by austinv11** [comment]
Due to overwhelming demand I have added it in the dev version. I hope to release 1.3 soon with it but I have just been really busy.
