### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [austinv11/PeripheralsPlusPlus#92]
Forge: 1448
Peripherals++: 1.3.0
Crash Report: http://pastebin.com/4Qjq8ZVt

Crash after updating PPP to the latest.

**Comment by SquidDev** [comment]
It looks like you're missing [Collective Framework](http://minecraft.curseforge.com/mc-mods/232966-collective-framework). It is now [required](http://www.computercraft.info/forums2/index.php?/topic/20903-mc-1710cc-165-173-peripherals-v130-miscperipherals-reimagined-includes-speakers-and-pocket-computer-upgrades/page__pid__227471__st__140#entry227471).

**Comment by Xiaminou** [comment]
Ooh, right, my bad, I even read it but completly forgot about it because I'm using Curse's launcher which usually automatically downloads dependencies.

**Comment by SquidDev** [comment]
@austinv11: You might want to include a dependency on Curse. You can do it automatically like [this](https://github.com/SquidDev-CC/CC-Tweaks/blob/master/gradle/scripts/upload.gradle#L50-L58).

**Comment by austinv11** [comment]
I actually do make both ComputerCraft and Collective Framework a required library. So it may be that curse is acting weird.

**Comment by Xiaminou** [comment]
Yeah I looked at the dependencies and it is included, so it's curse's fault.
