### ISSUE TITLE
[Suggestion|Issue] ME Bridge additional Lua command | keeps disappearing 

### ISSUE THREAD

**Issue by accessdenied0** [austinv11/PeripheralsPlusPlus#93]
Dear  @austinv11,

Like the title said I have the issue whenever I place a ME Bridge on a existing Me-cable (Network) it keeps disappearing. Any other function or the work around with: Placing first the ME Bridge and than connecting to the network do work...

In addition I have a suggestion for the ME Bridge is it possible add a lua command to list all pending crafting requests? I personally would like to program a Computer as Interface between a Smeltery and AE... In this case It would be very useful for me being able to read it out... what do you think about this?

access_denied

**Comment by grandmind** [comment]
Hi, I was unable to replicate your bug. What version of P++ and AE2 are you using?

**Comment by accessdenied0** [comment]
Here a list of all AE2 and Computercraft related mods: http://pastebin.com/S2gDvLwZ

**Comment by grandmind** [comment]
With all of those mods installed, and their dependencies, I was still unable to reproduce the bug.

**Comment by grandmind** [comment]
Are any exceptions thrown in console when you place the bridge?

**Comment by austinv11** [comment]
I like your suggestion, but I see no way of doing what you want in the AE api. I'll try sometime again, but for now I can't add it.

**Comment by accessdenied0** [comment]
@grandmind,

No very sorry... If there would be one I had it written in the op, sadly I just don't know for sure what is the possible cause. But I have to add MoreTurtles to the modlist which possibly interfere.

@austinv11, I glad you like the idea, I hope it will be possible in any time in the future.

**Comment by grandmind** [comment]
Hi, I'm trying to get as much information on this as possible so I can try to find out what might be causing it. I have a couple questions:
1. Can you replicate this in a newly-created superflat world? 
2. Can you replicate it with only Peripherals++ and CollectiveFramework installed?
3. If not, could I please get a list of all the mods you are using?
4. Are you placing the bridge in a different chunk than the main AE system?
5. What part of the system are you trying to connect it to? A wire, the controller, a drive, etc.?
